---
- name: add repository from PPA
  apt_repository:
    repo: ppa:maxmind/ppa

- name: install geoipupdate
  apt:
    name: geoipupdate
    update_cache: yes

- name: copy update script
  copy:
    src: files/geoipupdate.sh
    dest: /etc/cron.daily/geoipupdate
    mode: 0700
